//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myjobportal.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class address
    {
        public int id { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string pin { get; set; }
        public string state { get; set; }
        public string country { get; set; }
    }
}
