//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myjobportal.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class job
    {
        public int id { get; set; }
        public string jobdescription { get; set; }
        public int experienceinmonths { get; set; }
        public string expectedctc { get; set; }
        public string skills { get; set; }
        public string joblocation { get; set; }
        public string contactdetails { get; set; }
    }
}
