//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myjobportal.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class jobportaldbEntities : DbContext
    {
        public jobportaldbEntities()
            : base("name=jobportaldbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<address> addresses { get; set; }
        public virtual DbSet<candidate> candidates { get; set; }
        public virtual DbSet<company> companies { get; set; }
        public virtual DbSet<employer> employers { get; set; }
        public virtual DbSet<job> jobs { get; set; }
    }
}
